// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// prim_address_
std::string prim_address_(SEXP name, Environment env);
RcppExport SEXP lobstr_prim_address_(SEXP nameSEXP, SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type name(nameSEXP);
    Rcpp::traits::input_parameter< Environment >::type env(envSEXP);
    __result = Rcpp::wrap(prim_address_(name, env));
    return __result;
END_RCPP
}
// prim_refs_
int prim_refs_(SEXP name, Environment env);
RcppExport SEXP lobstr_prim_refs_(SEXP nameSEXP, SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type name(nameSEXP);
    Rcpp::traits::input_parameter< Environment >::type env(envSEXP);
    __result = Rcpp::wrap(prim_refs_(name, env));
    return __result;
END_RCPP
}
// prim_children_
RObject prim_children_(SEXP name, Environment env);
RcppExport SEXP lobstr_prim_children_(SEXP nameSEXP, SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type name(nameSEXP);
    Rcpp::traits::input_parameter< Environment >::type env(envSEXP);
    __result = Rcpp::wrap(prim_children_(name, env));
    return __result;
END_RCPP
}
// prim_desc
std::string prim_desc(SEXP x);
RcppExport SEXP lobstr_prim_desc(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    __result = Rcpp::wrap(prim_desc(x));
    return __result;
END_RCPP
}
// prim_length
int prim_length(SEXP x);
RcppExport SEXP lobstr_prim_length(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    __result = Rcpp::wrap(prim_length(x));
    return __result;
END_RCPP
}
// v_size
double v_size(double n, int size);
RcppExport SEXP lobstr_v_size(SEXP nSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    __result = Rcpp::wrap(v_size(n, size));
    return __result;
END_RCPP
}
// prim_sizes
double prim_sizes(List objects, Environment base_env);
RcppExport SEXP lobstr_prim_sizes(SEXP objectsSEXP, SEXP base_envSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type objects(objectsSEXP);
    Rcpp::traits::input_parameter< Environment >::type base_env(base_envSEXP);
    __result = Rcpp::wrap(prim_sizes(objects, base_env));
    return __result;
END_RCPP
}
// prim_type
std::string prim_type(RObject x);
RcppExport SEXP lobstr_prim_type(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RObject >::type x(xSEXP);
    __result = Rcpp::wrap(prim_type(x));
    return __result;
END_RCPP
}
