# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prim_address_ <- function(x) {
    .Call(`_lobstr_prim_address_`, x)
}

prim_addresses_ <- function(x) {
    .Call(`_lobstr_prim_addresses_`, x)
}

v_size <- function(n, size) {
    .Call(`_lobstr_v_size`, n, size)
}

prim_sizes <- function(objects, base_env) {
    .Call(`_lobstr_prim_sizes`, objects, base_env)
}

