# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prim_address_ <- function(name, env) {
    .Call(`_lobstr_prim_address_`, name, env)
}

prim_addresses_ <- function(name, env) {
    .Call(`_lobstr_prim_addresses_`, name, env)
}

prim_desc_ <- function(name, env) {
    .Call(`_lobstr_prim_desc_`, name, env)
}

prim_refs_ <- function(name, env) {
    .Call(`_lobstr_prim_refs_`, name, env)
}

v_size <- function(n, size) {
    .Call(`_lobstr_v_size`, n, size)
}

prim_sizes <- function(objects, base_env) {
    .Call(`_lobstr_prim_sizes`, objects, base_env)
}

prim_type_ <- function(name, env) {
    .Call(`_lobstr_prim_type_`, name, env)
}

